language: java
jdk:
  - oraclejdk8
sudo: false
env:
    - EXTRA_JAVA_HOMES=/usr/lib/jvm/java-8-oracle
before_script:
    - git clone --depth=1 https://github.com/smarr/mxtool.git
script:
    - mxtool/mx build
    - mxtool/mx unittest
    - mxtool/mx checkheaders
    - mxtool/mx checkcopyright
    - mxtool/mx checkstyle
    - mxtool/mx findbugs
