language: java
jdk:
  - oraclejdk8
sudo: false
script:
    - ./mx.sh build
    - ./mx.sh unittest
    - ./mx.sh checkheaders
    - ./mx.sh checkcopyright
    - ./mx.sh checkstyle
    - ./mx.sh findbugs
